source 'https://rubygems.org'
gem 'json', '~> 2.2'
gem 'logger', '~> 1.3'
gem 'filesize', '~> 0.2.0'
gem 'fileutils', '~> 1.2'
gem 'rubysl-prettyprint', '~> 2.0', '>= 2.0.3'
gem 'video_transcoding', '~> 0.25.1'
gem 'pry'
